-- 耗材与库存（小驼峰+审计与扩展）

CREATE TABLE `inventory_sku` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `storeId` BIGINT NOT NULL DEFAULT 0 COMMENT '门店/租户ID',
  `name` VARCHAR(128) NOT NULL COMMENT 'SKU名称',
  `category` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '品类',
  `unit` VARCHAR(16) NOT NULL DEFAULT 'pcs' COMMENT '计量单位',
  `safetyStock` INT NOT NULL DEFAULT 0 COMMENT '安全库存',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0停用 1启用',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  KEY `idx_store_cat` (`storeId`,`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存SKU';

CREATE TABLE `inventory_stock` (
  `skuId` BIGINT NOT NULL COMMENT 'SKU ID',
  `storeId` BIGINT NOT NULL COMMENT '门店/租户ID',
  `quantity` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`skuId`,`storeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存数量';

CREATE TABLE `inventory_ledger` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `skuId` BIGINT NOT NULL COMMENT 'SKU ID',
  `storeId` BIGINT NOT NULL COMMENT '门店/租户ID',
  `type` TINYINT NOT NULL COMMENT '类型 1入库 2出库 3调整',
  `quantity` INT NOT NULL COMMENT '数量(入正出负)',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  KEY `idx_sku_time` (`skuId`,`createTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存流水';