-- 基础服务（小驼峰+审计与扩展）

CREATE TABLE `file_object` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `storeId` BIGINT NOT NULL DEFAULT 0 COMMENT '门店/租户ID',
  `bucket` VARCHAR(64) NOT NULL COMMENT '桶名',
  `objectKey` VARCHAR(255) NOT NULL COMMENT '对象Key',
  `contentType` VARCHAR(64) NOT NULL COMMENT '内容类型',
  `size` BIGINT NOT NULL COMMENT '大小(byte)',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bucket_key` (`bucket`,`objectKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件对象';

CREATE TABLE `dict_type` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `storeId` BIGINT NOT NULL DEFAULT 0 COMMENT '门店/租户ID',
  `code` VARCHAR(64) NOT NULL COMMENT '字典编码',
  `name` VARCHAR(64) NOT NULL COMMENT '字典名称',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_code` (`storeId`,`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典类型';

CREATE TABLE `dict_item` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `typeId` BIGINT NOT NULL COMMENT '类型ID',
  `label` VARCHAR(64) NOT NULL COMMENT '显示文本',
  `value` VARCHAR(64) NOT NULL COMMENT '值',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  KEY `idx_type` (`typeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典项';

CREATE TABLE `notify_message` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `storeId` BIGINT NOT NULL DEFAULT 0 COMMENT '门店/租户ID',
  `userId` BIGINT NOT NULL COMMENT '用户ID',
  `title` VARCHAR(128) NOT NULL COMMENT '标题',
  `content` VARCHAR(500) NOT NULL COMMENT '内容',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0未读 1已读',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  KEY `idx_user_status` (`userId`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='站内消息';