spring:
  application:
    name: netbar-backend
  datasource:
    url: jdbc:h2:mem:netbar;MODE=MYSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

app:
  jwt:
    secret: change-this-secret
    expireMinutes: 43200

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger

