-- 活动与优惠（小驼峰+审计与扩展）

CREATE TABLE `campaign` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `storeId` BIGINT NOT NULL DEFAULT 0 COMMENT '门店/租户ID',
  `name` VARCHAR(64) NOT NULL COMMENT '活动名称',
  `type` TINYINT NOT NULL COMMENT '类型 1折扣 2满减 3限时',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0草稿 1生效 2下线',
  `startTime` DATETIME NULL COMMENT '开始时间',
  `endTime` DATETIME NULL COMMENT '结束时间',
  `rules` JSON NULL COMMENT '规则JSON',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  KEY `idx_store_status` (`storeId`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动';

CREATE TABLE `campaign_sku` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `campaignId` BIGINT NOT NULL COMMENT '活动ID',
  `skuId` BIGINT NOT NULL COMMENT 'SKU ID',
  `createBy` BIGINT NOT NULL DEFAULT 0 COMMENT '创建人ID',
  `createTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateBy` BIGINT NOT NULL DEFAULT 0 COMMENT '修改人ID',
  `updateTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `ext1` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段1',
  `ext2` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段2',
  `ext3` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段3',
  `ext4` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段4',
  `ext5` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '扩展字段5',
  PRIMARY KEY (`id`),
  KEY `idx_campaign` (`campaignId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动适用SKU';